name: youtube_muxer_2025
description: A Flutter plugin to mux (merge) video and audio files into one video file, with specific support for YouTube downloads.
version: 0.0.3
homepage: https://github.com/erfanalizada/youtube_muxer_2025

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  device_info_plus: ^10.1.0
  youtube_explode_dart: ^2.4.0
  video_player: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  plugin:
    platforms:
      android:
        package: com.example.youtube_muxer_2025
        pluginClass: YoutubeMuxer2025Plugin

# Optional: If you use custom fonts
# fonts:
#   - family: YourFontFamily
#     fonts:
#       - asset: fonts/YourFont.ttf
